name: autonitor
description: "A Flutter app to analyze your Twitter followers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.2.2
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: any
  flutter_inappwebview: ^6.0.0
  http: ^1.2.1
  dio: ^5.4.3
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  path: ^1.9.1
  path_provider: ^2.1.5
  async: ^2.13.0
  async_locks: ^4.0.2
  logger: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/suspended_banner.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/f1024.png"
  adaptive_icon_background: "#1A237E"
